### ISSUE TITLE
PDFtron does not load document on second visit to the WebViewer

### ISSUE THREAD

**Issue by hansaliyad1** [PDFTron/webviewer-salesforce#13]
Hello,

Happy holidays! I am creating this ticket because I am facing a problem with PDFtron on Salesforce. When Salesforce page loads and the user visits the record page, the Webviewer loads the document with no issue. If the user goes back and comes to the same record page or different record page, the document does not load. The user has to refresh the page for the document to load. So it looks like the page loads fine for the first time, but the user has to refresh the page to view it a second time. Without refresh, the document does not load the second time. Have you come across such issue before? I know I am missing something but not sure what.

I fire the event from connectedCallback() function to load the document. I tried debugging by having console log at different parts of the connectedCallback() function. The connectedCallback() is called everytime the user visits the page and I believe the event is fired.

Thank you!

Best,
hansaliyad1

**Comment by tommywintersr** [comment]
Hello,

Please open a ticket with support to help investigate the issue here:
https://www.pdftron.com/form/request/

Thanks,
Thomas

**Comment by hansaliyad1** [comment]
Thank Thomas! I created the ticket.

**Comment by danpercic86** [comment]
Hello! I have the same problem. Have you found any solution?

**Comment by tommywintersr** [comment]
Hi Dan,

Please review below answer and let me know if it works for your use case:

Sounds like this should be expected behaviour, since `connectedCallback()` is only called upon first insertion of a lightning web component into the DOM.
You can try moving your document load logic to `renderedCallback()` - this lifecycle hook is called every time when a LWC gets rendered.

For your reference, you can review LWC Lifecycle documentation here: https://developer.salesforce.com/docs/component-library/documentation/en/lwc/reference_lifecycle_hooks

Best,
Thomas
